"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- CONFIGURACIÓN DE SEGURIDAD PARA PRODUCCIÓN ---
# Si existe una variable de entorno SECRET_KEY, usa esa. Si no, usa la de desarrollo.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-=3#f_*0-a^w=*5k09)!o&wvootfqo!&qy*dzk5_#xgy6lsi#a*')

# DEBUG se vuelve False en producción automáticamente si pones la variable ENVIRONMENT=production
DEBUG = os.environ.get('ENVIRONMENT') != 'production'

# Permitir el dominio que te dé la plataforma de despliegue y localhost
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Librerías de terceros
    'corsheaders',
    'rest_framework',
    
    # Tus aplicaciones locales
    'productos',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # HASTA ARRIBA: Maneja permisos de conexión para el frontend
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Maneja archivos estáticos en producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# --- CONFIGURACIÓN DE BASE DE DATOS (SQLite Persistente) ---
# En producción buscaremos la ruta del disco persistente (/data/). 
# En desarrollo local usará la ruta del proyecto por defecto.
if os.environ.get('ENVIRONMENT') == 'production':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': '/data/db.sqlite3', 
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'es-es' # Configurado en Español

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# --- ARCHIVOS ESTÁTICOS (CSS, JavaScript) ---
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Optimización de almacenamiento de WhiteNoise para producción
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# --- ARCHIVOS MULTIMEDIA (Imágenes de productos) ---
MEDIA_URL = '/media/'

# Al igual que la base de datos, si estamos en producción las fotos van al disco persistente
if os.environ.get('ENVIRONMENT') == 'production':
    MEDIA_ROOT = '/data/media/'
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# --- CONFIGURACIÓN DE CORS ---
# Permite que cualquier frontend (React, Vue, Angular, etc.) consuma tu API sin bloqueos
CORS_ALLOW_ALL_ORIGINS = True

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --- CONFIGURACIÓN DE SEGURIDAD PARA PRODUCCIÓN ---
# Si existe una variable de entorno SECRET_KEY, usa esa. Si no, usa la de desarrollo.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-=3#f_*0-a^w=*5k09)!o&wvootfqo!&qy*dzk5_#xgy6lsi#a*')

# DEBUG se vuelve False en producción automáticamente si pones la variable ENVIRONMENT=production
DEBUG = os.environ.get('ENVIRONMENT') != 'production'

# Permitir el dominio que te dé la plataforma de despliegue y localhost
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Librerías de terceros
    'corsheaders',
    'rest_framework',
    
    # Tus aplicaciones locales
    'productos',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # HASTA ARRIBA: Maneja permisos de conexión para el frontend
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Maneja archivos estáticos en producción
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# --- CONFIGURACIÓN DE BASE DE DATOS (SQLite Persistente) ---
# En producción buscaremos la ruta del disco persistente (/data/). 
# En desarrollo local usará la ruta del proyecto por defecto.
if os.environ.get('ENVIRONMENT') == 'production':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': '/data/db.sqlite3', 
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'es-es' # Configurado en Español

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# --- ARCHIVOS ESTÁTICOS (CSS, JavaScript) ---
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Optimización de almacenamiento de WhiteNoise para producción
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# --- ARCHIVOS MULTIMEDIA (Imágenes de productos) ---
MEDIA_URL = '/media/'

# Al igual que la base de datos, si estamos en producción las fotos van al disco persistente
if os.environ.get('ENVIRONMENT') == 'production':
    MEDIA_ROOT = '/data/media/'
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# --- CONFIGURACIÓN DE CORS ---
# Permite que cualquier frontend (React, Vue, Angular, etc.) consuma tu API sin bloqueos
CORS_ALLOW_ALL_ORIGINS = True